name: CI - tests on PR

on:
  pull_request:
    branches: [ develop, main, build ]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f dependencies/requirements.txt ]; then python -m pip install -r dependencies/requirements.txt || true; fi
          if [ -f dependencies/requirements-dev.txt ]; then python -m pip install -r dependencies/requirements-dev.txt || true; fi

      - name: Run pytest
        run: python -m pytest -q
