name: PowerShell Tests (pwsh)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pwsh-tests:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PowerShell 7
        uses: PowerShell/PowerShellSetup@v1
        with:
          version: '7.4'

      - name: Install Pester 5
        shell: pwsh
        run: |
          Install-Module -Name Pester -Force -Scope CurrentUser -AllowClobber

      - name: Run Pester tests
        shell: pwsh
        run: |
          Import-Module Pester -Force
          Invoke-Pester -Script tests -Output Detailed

      - name: Run Script Analyzer
        shell: pwsh
        run: |
          Install-Module -Name PSScriptAnalyzer -Force -Scope CurrentUser
          Invoke-ScriptAnalyzer -Path . -Recurse -Severity Warning,Error | Format-Table FilePath,Line,RuleName,Message -AutoSize
